/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Error,
} from './models/Error';
import {
  EventEmitter,
} from '@stencil/core';
import {
  Offer,
} from './models/Offer';
import {
  Location,
} from './models/location';


export namespace Components {

  interface ErrorDisplay {
    'error': Error;
  }
  interface ErrorDisplayAttributes extends StencilHTMLAttributes {
    'error'?: Error;
  }

  interface MainContainer {}
  interface MainContainerAttributes extends StencilHTMLAttributes {
    'onErrorOccured'?: (event: CustomEvent<Error>) => void;
  }

  interface NoResultFound {}
  interface NoResultFoundAttributes extends StencilHTMLAttributes {}

  interface OfferCardList {
    'offerList': Offer[];
  }
  interface OfferCardListAttributes extends StencilHTMLAttributes {
    'offerList'?: Offer[];
  }

  interface OfferCard {
    'offer': Offer;
  }
  interface OfferCardAttributes extends StencilHTMLAttributes {
    'offer'?: Offer;
  }

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {
    'onOnDateChange'?: (event: CustomEvent<any>) => void;
  }

  interface DurationDropdown {}
  interface DurationDropdownAttributes extends StencilHTMLAttributes {
    'onOnDurationChange'?: (event: CustomEvent<any>) => void;
  }

  interface LocationContainer {}
  interface LocationContainerAttributes extends StencilHTMLAttributes {
    'onCleanError'?: (event: CustomEvent<any>) => void;
    'onErrorOccured'?: (event: CustomEvent<Error>) => void;
  }

  interface LocationListItem {
    'location': Location;
  }
  interface LocationListItemAttributes extends StencilHTMLAttributes {
    'location'?: Location;
    'onOnSelectLocation'?: (event: CustomEvent<Location>) => void;
  }

  interface LocationList {
    'locations': Location[];
  }
  interface LocationListAttributes extends StencilHTMLAttributes {
    'locations'?: Location[];
  }

  interface LocationSearch {
    'locationName': string;
    'searchString': string;
  }
  interface LocationSearchAttributes extends StencilHTMLAttributes {
    'locationName'?: string;
    'onOnLocationInputChange'?: (event: CustomEvent<any>) => void;
    'onOnLocationInputFocus'?: (event: CustomEvent<any>) => void;
    'searchString'?: string;
  }

  interface SearchBar {}
  interface SearchBarAttributes extends StencilHTMLAttributes {
    'onOnSubmit'?: (event: CustomEvent<any>) => void;
  }

  interface SearchButton {}
  interface SearchButtonAttributes extends StencilHTMLAttributes {}

  interface TopBanner {}
  interface TopBannerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ErrorDisplay': Components.ErrorDisplay;
    'MainContainer': Components.MainContainer;
    'NoResultFound': Components.NoResultFound;
    'OfferCardList': Components.OfferCardList;
    'OfferCard': Components.OfferCard;
    'DatePicker': Components.DatePicker;
    'DurationDropdown': Components.DurationDropdown;
    'LocationContainer': Components.LocationContainer;
    'LocationListItem': Components.LocationListItem;
    'LocationList': Components.LocationList;
    'LocationSearch': Components.LocationSearch;
    'SearchBar': Components.SearchBar;
    'SearchButton': Components.SearchButton;
    'TopBanner': Components.TopBanner;
  }

  interface StencilIntrinsicElements {
    'error-display': Components.ErrorDisplayAttributes;
    'main-container': Components.MainContainerAttributes;
    'no-result-found': Components.NoResultFoundAttributes;
    'offer-card-list': Components.OfferCardListAttributes;
    'offer-card': Components.OfferCardAttributes;
    'date-picker': Components.DatePickerAttributes;
    'duration-dropdown': Components.DurationDropdownAttributes;
    'location-container': Components.LocationContainerAttributes;
    'location-list-item': Components.LocationListItemAttributes;
    'location-list': Components.LocationListAttributes;
    'location-search': Components.LocationSearchAttributes;
    'search-bar': Components.SearchBarAttributes;
    'search-button': Components.SearchButtonAttributes;
    'top-banner': Components.TopBannerAttributes;
  }


  interface HTMLErrorDisplayElement extends Components.ErrorDisplay, HTMLStencilElement {}
  var HTMLErrorDisplayElement: {
    prototype: HTMLErrorDisplayElement;
    new (): HTMLErrorDisplayElement;
  };

  interface HTMLMainContainerElement extends Components.MainContainer, HTMLStencilElement {}
  var HTMLMainContainerElement: {
    prototype: HTMLMainContainerElement;
    new (): HTMLMainContainerElement;
  };

  interface HTMLNoResultFoundElement extends Components.NoResultFound, HTMLStencilElement {}
  var HTMLNoResultFoundElement: {
    prototype: HTMLNoResultFoundElement;
    new (): HTMLNoResultFoundElement;
  };

  interface HTMLOfferCardListElement extends Components.OfferCardList, HTMLStencilElement {}
  var HTMLOfferCardListElement: {
    prototype: HTMLOfferCardListElement;
    new (): HTMLOfferCardListElement;
  };

  interface HTMLOfferCardElement extends Components.OfferCard, HTMLStencilElement {}
  var HTMLOfferCardElement: {
    prototype: HTMLOfferCardElement;
    new (): HTMLOfferCardElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLDurationDropdownElement extends Components.DurationDropdown, HTMLStencilElement {}
  var HTMLDurationDropdownElement: {
    prototype: HTMLDurationDropdownElement;
    new (): HTMLDurationDropdownElement;
  };

  interface HTMLLocationContainerElement extends Components.LocationContainer, HTMLStencilElement {}
  var HTMLLocationContainerElement: {
    prototype: HTMLLocationContainerElement;
    new (): HTMLLocationContainerElement;
  };

  interface HTMLLocationListItemElement extends Components.LocationListItem, HTMLStencilElement {}
  var HTMLLocationListItemElement: {
    prototype: HTMLLocationListItemElement;
    new (): HTMLLocationListItemElement;
  };

  interface HTMLLocationListElement extends Components.LocationList, HTMLStencilElement {}
  var HTMLLocationListElement: {
    prototype: HTMLLocationListElement;
    new (): HTMLLocationListElement;
  };

  interface HTMLLocationSearchElement extends Components.LocationSearch, HTMLStencilElement {}
  var HTMLLocationSearchElement: {
    prototype: HTMLLocationSearchElement;
    new (): HTMLLocationSearchElement;
  };

  interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {}
  var HTMLSearchBarElement: {
    prototype: HTMLSearchBarElement;
    new (): HTMLSearchBarElement;
  };

  interface HTMLSearchButtonElement extends Components.SearchButton, HTMLStencilElement {}
  var HTMLSearchButtonElement: {
    prototype: HTMLSearchButtonElement;
    new (): HTMLSearchButtonElement;
  };

  interface HTMLTopBannerElement extends Components.TopBanner, HTMLStencilElement {}
  var HTMLTopBannerElement: {
    prototype: HTMLTopBannerElement;
    new (): HTMLTopBannerElement;
  };

  interface HTMLElementTagNameMap {
    'error-display': HTMLErrorDisplayElement
    'main-container': HTMLMainContainerElement
    'no-result-found': HTMLNoResultFoundElement
    'offer-card-list': HTMLOfferCardListElement
    'offer-card': HTMLOfferCardElement
    'date-picker': HTMLDatePickerElement
    'duration-dropdown': HTMLDurationDropdownElement
    'location-container': HTMLLocationContainerElement
    'location-list-item': HTMLLocationListItemElement
    'location-list': HTMLLocationListElement
    'location-search': HTMLLocationSearchElement
    'search-bar': HTMLSearchBarElement
    'search-button': HTMLSearchButtonElement
    'top-banner': HTMLTopBannerElement
  }

  interface ElementTagNameMap {
    'error-display': HTMLErrorDisplayElement;
    'main-container': HTMLMainContainerElement;
    'no-result-found': HTMLNoResultFoundElement;
    'offer-card-list': HTMLOfferCardListElement;
    'offer-card': HTMLOfferCardElement;
    'date-picker': HTMLDatePickerElement;
    'duration-dropdown': HTMLDurationDropdownElement;
    'location-container': HTMLLocationContainerElement;
    'location-list-item': HTMLLocationListItemElement;
    'location-list': HTMLLocationListElement;
    'location-search': HTMLLocationSearchElement;
    'search-bar': HTMLSearchBarElement;
    'search-button': HTMLSearchButtonElement;
    'top-banner': HTMLTopBannerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
